# Generated by Django 3.2.12 on 2023-04-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='visitors_need',
            new_name='visitors_per_day',
        ),
    ]
