# Generated by Django 3.2.12 on 2023-04-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0002_rename_visitors_need_ad_visitors_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
